const dasseya1User = {
    "login": "dasseya1",
    "id": 3190320,
    "avatar_url": "https://avatars2.githubusercontent.com/u/3190320?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dasseya1",
    "html_url": "https://github.com/dasseya1",
    "followers_url": "https://api.github.com/users/dasseya1/followers",
    "following_url": "https://api.github.com/users/dasseya1/following{/other_user}",
    "gists_url": "https://api.github.com/users/dasseya1/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dasseya1/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dasseya1/subscriptions",
    "organizations_url": "https://api.github.com/users/dasseya1/orgs",
    "repos_url": "https://api.github.com/users/dasseya1/repos",
    "events_url": "https://api.github.com/users/dasseya1/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dasseya1/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Damien Asseya",
    "company": null,
    "blog": "https://www.linkedin.com/in/damienasseya",
    "location": "Manassas, VA",
    "email": null,
    "hireable": true,
    "bio": null,
    "public_repos": 43,
    "public_gists": 0,
    "followers": 1,
    "following": 6,
    "created_at": "2013-01-05T03:10:07Z",
    "updated_at": "2017-06-20T14:09:19Z"
}

export default dasseya1User