const nxanttopoulosUser = {
    "login": "nxanttopoulos",
    "id": 25088349,
    "avatar_url": "https://avatars1.githubusercontent.com/u/25088349?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nxanttopoulos",
    "html_url": "https://github.com/nxanttopoulos",
    "followers_url": "https://api.github.com/users/nxanttopoulos/followers",
    "following_url": "https://api.github.com/users/nxanttopoulos/following{/other_user}",
    "gists_url": "https://api.github.com/users/nxanttopoulos/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nxanttopoulos/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nxanttopoulos/subscriptions",
    "organizations_url": "https://api.github.com/users/nxanttopoulos/orgs",
    "repos_url": "https://api.github.com/users/nxanttopoulos/repos",
    "events_url": "https://api.github.com/users/nxanttopoulos/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nxanttopoulos/received_events",
    "type": "User",
    "site_admin": false,
    "name": null,
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "public_repos": 20,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2017-01-12T20:14:15Z",
    "updated_at": "2017-05-17T22:28:04Z"
}

export default nxanttopoulosUser